### ISSUE TITLE
App unresponsive 

### ISSUE THREAD

**Issue by odopo** [NaeemBolchhi/MiX-HTTP-File-Server-Redesigned#1]
I tried modifying the app in an apk editor and placing the 2 htm files and the folder with the other related files at assets/server and building it. Is this the correct location to place the files? App launches and flashes and nothing happens. It doesn't ask for permissions. I can launch the server through Quick Settings tile and start the server. It shows your mod in browser but it only shows folders and not files (irrespective of the sidebar options) and uploads etc. don't work. Is this because the app didn't get required permissions? The app won't normally start.

I'm on Android 14 and going to permission settings only display Music and audio, Photos and videos as options I can enable. Normal unmodified app shows a popup asking for access to all files permission upon initial launch. What am I doing strong? Can you help?

**Comment by NaeemBolchhi** [comment]
The app has a license verification check that needs to be disabled before you can modify it. I only know of the infamous yellow smileyface app to be able to do that. Try apksigner and confirm that the app still opens and works normally with a new license. This modifed apk can now be edited with apktool and repackaged into a new apk. Sign the new apk and you have a working mod of the app.

**Comment by odopo** [comment]
Thanks! Apktool M worked for all of that.
